name: bpx_remote_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - numpy=1.26.4
  - pandas=2.2.3
  - scikit-learn=1.1.0
  - pip:
      - bpx-net  # Conda 会自动去 PyPI 寻找并下载
